-- MySQL Script generated by MySQL Workbench
-- Wed Nov 10 14:56:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema swap
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_username` VARCHAR(60) NOT NULL,
  `user_password` VARCHAR(60) NOT NULL,
  `user_fname` VARCHAR(60) NOT NULL,
  `user_lname` VARCHAR(60) NOT NULL,
  `user_number` VARCHAR(45) NOT NULL,
  `date_of_signup` VARCHAR(45) NOT NULL,
  `user_security_primaryschool` VARCHAR(45) NOT NULL,
  `user_security_favoritefood` VARCHAR(45) NOT NULL,
  `user_card_type` VARCHAR(45) NULL,
  `user_card_number` VARCHAR(16) NULL,
  `user_card_expiry` VARCHAR(45) NULL,
  `user_card_code` VARCHAR(3) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `user_username_UNIQUE` (`user_username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`store` (
  `store_id` INT NOT NULL AUTO_INCREMENT,
  `store_name` VARCHAR(100) NOT NULL,
  `store_pricepoint` VARCHAR(1) NOT NULL,
  `store_about` VARCHAR(1024) NOT NULL,
  `store_picone` VARCHAR(100) NULL,
  `store_pictwo` VARCHAR(100) NULL,
  `store_picethree` VARCHAR(100) NULL,
  `store_address` VARCHAR(45) NULL,
  `store_number` VARCHAR(45) NULL,
  `store_url` VARCHAR(45) NULL,
  PRIMARY KEY (`store_id`),
  UNIQUE INDEX `store_id_UNIQUE` (`store_id` ASC),
  UNIQUE INDEX `store_name_UNIQUE` (`store_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`all_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`all_products` (
  `product_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `product_name` VARCHAR(45) NULL,
  `product_pirce` VARCHAR(45) NULL,
  `product_about` VARCHAR(45) NULL,
  `product_picone` VARCHAR(45) NULL,
  `product_pictwo` VARCHAR(45) NULL,
  `product_picthree` VARCHAR(45) NULL,
  PRIMARY KEY (`product_id`),
  CONSTRAINT `store_id_product`
    FOREIGN KEY (`store_id`)
    REFERENCES `mydb`.`store` (`store_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_past_purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_past_purchases` (
  `purchase_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `purchase_time` VARCHAR(45) NOT NULL,
  `purchase_quantity` VARCHAR(45) NOT NULL,
  `purchase_cost` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`purchase_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `store_id_idx` (`store_id` ASC),
  INDEX `product_id_idx` (`product_id` ASC),
  CONSTRAINT `user_id_purchase`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_id_purchase`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`all_products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `store_id_purchase`
    FOREIGN KEY (`store_id`)
    REFERENCES `mydb`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `cat_id` INT NOT NULL,
  `cat_type` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`store_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`store_category` (
  `storecat_id` INT NOT NULL,
  `cat_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`storecat_id`),
  INDEX `cat_id_idx` (`cat_id` ASC),
  INDEX `store_id_idx` (`store_id` ASC),
  CONSTRAINT `cat_id_storecat`
    FOREIGN KEY (`cat_id`)
    REFERENCES `mydb`.`category` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `store_id_storecat`
    FOREIGN KEY (`store_id`)
    REFERENCES `mydb`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`working_employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`working_employees` (
  `working_id` INT NOT NULL,
  `working_fname` VARCHAR(45) NOT NULL,
  `working_lname` VARCHAR(45) NOT NULL,
  `working_number` VARCHAR(45) NULL,
  `working_address` VARCHAR(45) NULL,
  `working_role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`working_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee_attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee_attendance` (
  `attendance_id` INT NOT NULL,
  `working_id` INT NOT NULL,
  `attendance_date` VARCHAR(45) NOT NULL,
  `attendance_in_time` VARCHAR(45) NOT NULL,
  `attendance_out_time` VARCHAR(45) NOT NULL,
  `attendance_absent_reason` VARCHAR(45) NULL,
  PRIMARY KEY (`attendance_id`),
  INDEX `working_id_idx` (`working_id` ASC),
  CONSTRAINT `working_id_attendance`
    FOREIGN KEY (`working_id`)
    REFERENCES `mydb`.`working_employees` (`working_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`total_people_in_lab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`total_people_in_lab` (
  `total_id` INT NOT NULL,
  `total_maximum` INT NOT NULL,
  `total_current` INT NOT NULL,
  PRIMARY KEY (`total_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`place` (
  `place_id` INT NOT NULL,
  `place_name` VARCHAR(45) NULL,
  `place_status` VARCHAR(45) NULL,
  `place_limit` INT NULL,
  PRIMARY KEY (`place_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_booking` (
  `booking_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `place_id` INT NOT NULL,
  `booking_start` VARCHAR(45) NULL,
  `booking_end` VARCHAR(45) NULL,
  `booking_status` INT NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `place_id_idx` (`place_id` ASC),
  CONSTRAINT `user_id_booking`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `place_id_booking`
    FOREIGN KEY (`place_id`)
    REFERENCES `mydb`.`place` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
