-- MySQL Script generated by MySQL Workbench
-- Wed Nov 24 15:31:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema swap
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_username` VARCHAR(60) NOT NULL,
  `user_password` VARCHAR(60) NOT NULL,
  `user_fname` VARCHAR(60) NOT NULL,
  `user_lname` VARCHAR(60) NOT NULL,
  `user_role` INT NOT NULL,
  `username_email` VARCHAR(200) NOT NULL,
  `user_number` VARCHAR(45) NOT NULL,
  `date_of_signup` VARCHAR(45) NOT NULL,
  `user_security_primaryschool` VARCHAR(45) NOT NULL,
  `user_security_favoritefood` VARCHAR(45) NOT NULL,
  `user_secret` VARCHAR(255) NOT NULL,
  `user_card_type` VARCHAR(45) NULL,
  `user_card_number` VARCHAR(16) NULL,
  `user_card_expiry` VARCHAR(45) NULL,
  `user_card_code` VARCHAR(3) NULL,
  `userscol` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) ,
  UNIQUE INDEX `user_username_UNIQUE` (`user_username` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` TEXT NULL,
  `product_price` FLOAT NULL,
  `product_about` TEXT NULL,
  `product_picone` VARCHAR(200) NULL,
  `product_pictwo` VARCHAR(200) NULL,
  `product_picthree` VARCHAR(200) NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`store` (
  `store_id` INT NOT NULL AUTO_INCREMENT,
  `store_name` TEXT NOT NULL,
  `store_pricepoint` INT(1) NOT NULL,
  `store_about` TEXT NOT NULL,
  `store_picone` VARCHAR(200) NULL,
  `store_pictwo` VARCHAR(200) NULL,
  `store_picethree` VARCHAR(200) NULL,
  `store_address` VARCHAR(100) NULL,
  `store_number` VARCHAR(45) NULL,
  `store_url` VARCHAR(150) NULL,
  `store_status` INT(1) NULL,
  PRIMARY KEY (`store_id`),
  UNIQUE INDEX `store_id_UNIQUE` (`store_id` ASC) ,
  UNIQUE INDEX `store_name_UNIQUE` (`store_name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `type_choice` VARCHAR(45) NOT NULL,
  `additional_costs` FLOAT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_past_purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_past_purchases` (
  `purchase_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  `purchase_time` VARCHAR(45) NOT NULL,
  `purchase_quantity` VARCHAR(45) NOT NULL,
  `purchase_cost` FLOAT NOT NULL,
  `purchase_status` INT(1) NULL,
  PRIMARY KEY (`purchase_id`),
  INDEX `user_id_idx` (`user_id` ASC) ,
  INDEX `store_id_idx` (`store_id` ASC) ,
  INDEX `product_id_idx` (`product_id` ASC) ,
  INDEX `type_id_purchase_idx` (`type_id` ASC) ,
  CONSTRAINT `user_id_purchase`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_id_purchase`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `store_id_purchase`
    FOREIGN KEY (`store_id`)
    REFERENCES `mydb`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `type_id_purchase`
    FOREIGN KEY (`type_id`)
    REFERENCES `mydb`.`type` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_type` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`storecat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`storecat` (
  `cat_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  INDEX `cat_id_idx` (`cat_id` ASC) ,
  INDEX `store_id_idx` (`store_id` ASC) ,
  CONSTRAINT `cat_id_storecat`
    FOREIGN KEY (`cat_id`)
    REFERENCES `mydb`.`category` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `store_id_storecat`
    FOREIGN KEY (`store_id`)
    REFERENCES `mydb`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`working_employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`working_employees` (
  `working_id` INT NOT NULL AUTO_INCREMENT,
  `working_fname` VARCHAR(45) NOT NULL,
  `working_lname` VARCHAR(45) NOT NULL,
  `working_role` VARCHAR(45) NOT NULL,
  `working_number` VARCHAR(45) NULL,
  `working_address` VARCHAR(150) NULL,
  PRIMARY KEY (`working_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee_attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee_attendance` (
  `attendance_id` INT NOT NULL AUTO_INCREMENT,
  `working_id` INT NOT NULL,
  `attendance_date` VARCHAR(45) NOT NULL,
  `attendance_in_time` VARCHAR(4) NOT NULL,
  `attendance_out_time` VARCHAR(4) NOT NULL,
  `attendance_valid_absence` INT(1) NULL,
  PRIMARY KEY (`attendance_id`),
  INDEX `working_id_idx` (`working_id` ASC) ,
  CONSTRAINT `working_id_attendance`
    FOREIGN KEY (`working_id`)
    REFERENCES `mydb`.`working_employees` (`working_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`total_people_in_lab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`total_people_in_lab` (
  `total_id` INT NOT NULL AUTO_INCREMENT,
  `total_maximum` INT NOT NULL,
  `total_current` INT NOT NULL,
  PRIMARY KEY (`total_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`place` (
  `place_id` INT NOT NULL AUTO_INCREMENT,
  `place_name` VARCHAR(45) NOT NULL,
  `place_status` VARCHAR(45) NOT NULL,
  `place_limit` INT NOT NULL,
  `time_start` VARCHAR(4) NOT NULL,
  `time_end` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`place_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_booking` (
  `booking_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `place_id` INT NOT NULL,
  `booking_start` VARCHAR(4) NULL,
  `booking_end` VARCHAR(4) NULL,
  `booking_status` INT NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `user_id_idx` (`user_id` ASC) ,
  INDEX `place_id_idx` (`place_id` ASC) ,
  CONSTRAINT `user_id_booking`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `place_id_booking`
    FOREIGN KEY (`place_id`)
    REFERENCES `mydb`.`place` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_type` (
  `product_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `type_id`),
  INDEX `prodtype_product_id_idx` (`product_id` ASC) ,
  INDEX `prodtype_type_id_idx` (`type_id` ASC) ,
  CONSTRAINT `prodtype_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prodtype_type_id`
    FOREIGN KEY (`type_id`)
    REFERENCES `mydb`.`type` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`storeprod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`storeprod` (
  `store_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`store_id`, `product_id`),
  INDEX `storeprod_product_id_idx` (`product_id` ASC) ,
  CONSTRAINT `storeprod_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `mydb`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `storeprod_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employees_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employees_task` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `working_id` INT NOT NULL,
  `task_name` TEXT(1024) NOT NULL,
  `task_progress` VARCHAR(9) NOT NULL,
  `task_employees_taskcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`task_id`),
  INDEX `task_working_id_idx` (`working_id` ASC) ,
  CONSTRAINT `task_working_id`
    FOREIGN KEY (`working_id`)
    REFERENCES `mydb`.`working_employees` (`working_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_cart` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  `quantity` VARCHAR(45) NULL,
  PRIMARY KEY (`cart_id`),
  INDEX `product_id_cart_idx` (`product_id` ASC) ,
  INDEX `type_id_cart_idx` (`type_id` ASC) ,
  INDEX `user_id_cart_idx` (`user_id` ASC) ,
  CONSTRAINT `product_id_cart`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `type_id_cart`
    FOREIGN KEY (`type_id`)
    REFERENCES `mydb`.`type` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id_cart`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
