<?php

//checks for empty boxes
function emptyInputSignup($name, $email, $username, $pwd, $pwdRepeat)
{
    $result = false;
    if (empty($name) || empty($email) || empty($username) || empty($pwd) || empty($pwdRepeat)) {
        $result = true;
    } else {
        $result = false;
    }
    return $result;
}
//checks username input (im not sure what the error is here)
function invalidUid($username)
{
    $result = false;
    if (!preg_match("/^[a-zA-Z0-9]*$/", $username)) {
        $result = true;
    } else {
        $result = false;
    }
    return $result;
}

//checks if an email exists
function invalidEmail($email)
{
    $result = false;
    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        $result = true;
    } else {
        $result = false;
    }
    return $result;
}
//checks if passwords match also used for otp verification
function pwdMatch($pwd, $pwdRepeat)
{
    $result = false;
    if ($pwd !== $pwdRepeat) {
        $result = true;
        echo "true" . $result;
    } else {
        $result = false;
        echo "false" . $result;
    }

    return $result;
}

// check if username already exists AND if it exists returns the values of the user
// creates prepared statements so it runs into the db without input?
function uidExists($conn, $username, $email)
{
    $sql = "SELECT * FROM users WHERE user_username =? OR username_email =?;";
    $stmt = mysqli_stmt_init($conn);
    if (!mysqli_stmt_prepare($stmt, $sql)) {
        header("location: ../swapproj/signup?error=stmtfailed");
        exit();
    }

    mysqli_stmt_bind_param($stmt, "ss", $username, $email);
    mysqli_stmt_execute($stmt);

    $resultData = mysqli_stmt_get_result($stmt);

    //RETURNS THE DATA FROM THE TABLE AND STORES IT IN $ROW
    //THIS WAY WE CAN USE IT FOR LOGGING IN
    if ($row = mysqli_fetch_assoc($resultData)) {
        return $row;
    } else {
        $result = false;
        return $result;
    }

    mysqli_stmt_close($stmt);
}

######ATTENTION ADDED 1 MORE COLUMN IN SQL DATABASE CALLED USER_SECRET FOR GOOGLE AUTH
// check if username already exists 
// creates prepared statements so it runs into the db without input?
function createUser($conn, $firstname, $lastname, $email, $username, $pwd, $phonenumber, $primaryschool, $favouritefood)
{
    $sql = "INSERT INTO users (user_username, user_password, user_fname, user_lname, username_email, user_number, date_of_signup,user_security_primaryschool, user_security_favoritefood, user_secret) VALUES (?,?,?,?,?,?,?,?,?,?);";
    $stmt = mysqli_stmt_init($conn);

    if (!mysqli_stmt_prepare($stmt, $sql)) {
        header("location: ../swapproj/signup?error=stmtfailed");
        exit();
    }
    $pepper = "AWiokdfnkFNKKHHDBJXLL28838jkuiu54859dnkkmid93E1928485";
    //password hashing
    //we created a pepper that will persist across all users, the purpose is to secure the password such that people will need access to this file to read the pepper
    //next we hashed that with sha256, then hashed it over with sha256 2 times more.
    //Lastly it's hashed using password_hash together with a secret salt autogenerated by the password_hash function
    $hashedPwd = hash_hmac("sha256",$pwd,$pepper);
    $hashedPwd = hash("sha256",hash("sha256",$hashedPwd));
    $hashedPwd = password_hash($hashedPwd, PASSWORD_DEFAULT);


    $randomsecret = generateRandomString();
    $date = date('m/d/Y h:i:s a', time());

    // number of 's' indicate number of values? for some reason, and i used placeholder for all the unsupplied values
    

    mysqli_stmt_bind_param($stmt, "ssssssssss", $username, $hashedPwd, $firstname, $lastname, $email, $phonenumber, $date, $primaryschool, $favouritefood, $randomsecret);
    mysqli_stmt_execute($stmt);
    //closes the connection
    mysqli_stmt_close($stmt);


    header("location: ../swapproj/signup?error=none");
    exit();
}
// Function to generate random secret for google auth
function generateRandomString($length = 16)
{
    $characters = '234567QWERTYUIOPASDFGHJKLZXCVBNM';
    $charactersLength = strlen($characters);
    $randomString = '';
    for ($i = 0; $i < $length; $i++) {
        $randomString .= $characters[rand(0, $charactersLength - 1)];
    }
    return $randomString;
}


//////////////LOGIN FUNCTIONS////////////////
//checks for empty input boxes
function emptyInputLogin($username, $pwd)
{
    $result = false;
    if (empty($username) || empty($pwd)) {
        $result = true;
    } else {
        $result = false;
    }
    return $result;
}

//checks for email otp
function verification2fa($email)
{
    $result = false;
    if (empty($username) || empty($pwd)) {
        $result = true;
    } else {
        $result = false;
    }
    return $result;
}

//logs in user whether username or email is used
function loginUser($conn, $username, $pwd)
{
    $uidExists = uidExists($conn, $username, $username);

    if ($uidExists === false) {
        header("location: ../swapproj/login?error=wronglogin");
        exit();
    }
    $pepper = "AWiokdfnkFNKKHHDBJXLL28838jkuiu54859dnkkmid93E1928485";
    $pwdHashed = $uidExists["user_password"];
    $pwd = hash_hmac("sha256",$pwd,$pepper);
    $pwd = hash("sha256",hash("sha256",$pwd));
    $checkPwd = password_verify($pwd, $pwdHashed);

    if ($checkPwd === false) {
        header("location: ../swapproj/login?error=wronglogin");
        exit();
    } elseif ($checkPwd === true) {
        // OTP email

        $vc = new VerificationCode($uidExists["username_email"]);
        $vc->sendMail(); // MAIL SENT SUCCESSFULLY

        //Taking the current time
        $_SESSION['start'] = time();
        //Setting the time to end session
        $_SESSION['expire'] = $_SESSION['start'] + (200);

        //session superglobal
        $_SESSION["userid"] = $uidExists["user_id"];
        $_SESSION["username"] = $uidExists["user_username"];
        $_SESSION["useremail"] = $uidExists["username_email"];
        $_SESSION["role"] = $uidExists["user_role"];
        $_SESSION["loginstate"] = "A";
        $_SESSION['LAST_ACTIVE_TIME']=time();

        header("location: ../swapproj/emailverification");
        exit();
    }
}
//checks for empty input boxes
function failedCaptcha($captcha)
{
    $result = false;
    if (!isset($captcha) || empty($captcha)) {
        //runs if captcha is empty

        $result = "empty captcha";
        echo $result;
    } else {
        //runs if captcha received input
        $secret = '6LceTzMdAAAAAOpz-EsYoCKZGnAXCzF3lv-FsFfF';

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, 'https://www.google.com/recaptcha/api/siteverify?secret=' . $secret . '&response=' . $captcha);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $response = curl_exec($ch);
        curl_close($ch);
        $response = json_decode($response);

        if ($response->success) {
            // What happens when the CAPTCHA was entered incorrectly
            $result = true;
            echo "bad captcha";
        } else {
            // Your code here to handle a successful verification
            $result = false;
            echo "good captcha";
        }
    }
    return $result;
}
