<?php

//checks for empty boxes
function emptyInputSignup($name, $email, $username, $pwd, $pwdRepeat)
{
    $result = false;
    if (empty($name) || empty($email) || empty($username) || empty($pwd) || empty($pwdRepeat)) {
        $result = true;
    } else {
        $result = false;
    }
    return $result;
}
//checks username input (im not sure what the error is here)
function invalidUid($username)
{
    $result = false;
    if (!preg_match("/^[a-zA-Z0-9]*$/", $username)) {
        $result = true;
    } else {
        $result = false;
    }
    return $result;
}

//checks if an email exists
function invalidEmail($email)
{
    $result = false;
    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        $result = true;
    } else {
        $result = false;
    }
    return $result;
}
//checks if passwords match also used for otp verification
function pwdMatch($pwd, $pwdRepeat)
{
    $result = false;
    if ($pwd !== $pwdRepeat) {
        $result = true;
        echo "true" . $result;
    } else {
        $result = false;
        echo "false" . $result;
    }

    return $result;
}

// check if username already exists AND if it exists returns the values of the user
// creates prepared statements so it runs into the db without input?
function uidExists($conn, $username, $email)
{
    $sql = "SELECT * FROM users WHERE user_username =? OR username_email =?;";
    $stmt = mysqli_stmt_init($conn);
    if (!mysqli_stmt_prepare($stmt, $sql)) {
        header("location: ../swapproj/signup?error=stmtfailed");
        exit();
    }

    mysqli_stmt_bind_param($stmt, "ss", $username, $email);
    mysqli_stmt_execute($stmt);

    $resultData = mysqli_stmt_get_result($stmt);

    //RETURNS THE DATA FROM THE TABLE AND STORES IT IN $ROW
    //THIS WAY WE CAN USE IT FOR LOGGING IN
    if ($row = mysqli_fetch_assoc($resultData)) {
        return $row;
    } else {
        $result = false;
        return $result;
    }

    mysqli_stmt_close($stmt);
}

######ATTENTION ADDED 1 MORE COLUMN IN SQL DATABASE CALLED USER_SECRET FOR GOOGLE AUTH
// check if username already exists 
// creates prepared statements so it runs into the db without input?
function createUser($conn, $firstname, $lastname, $email, $username, $pwd, $phonenumber, $primaryschool, $favouritefood)
{
    session_start();
    $sql = "INSERT INTO users (user_username, user_password, user_fname, user_lname, username_email, user_number, date_of_signup,user_security_primaryschool, user_security_favoritefood, user_secret) VALUES (?,?,?,?,?,?,?,?,?,?);";
    $stmt = mysqli_stmt_init($conn);

    if (!mysqli_stmt_prepare($stmt, $sql)) {
        header("location: ../swapproj/signup?error=stmtfailed");
        exit();
    }


    //hashing
    $pepper = "AWiokdfnkFNKKHHDBJXLL28838jkuiu54859dnkkmid93E1928485";
    //password hashing
    //we created a pepper that will persist across all users, the purpose is to secure the password such that people will need access to this file to read the pepper
    //next we hashed that with sha256, then hashed it over with sha256 2 times more.
    //Lastly it's hashed using password_hash together with a secret salt autogenerated by the password_hash function
    $hashedPwd = hash_hmac("sha256", $pwd, $pepper);
    $hashedPwd = hash("sha256", hash("sha256", $hashedPwd));
    $hashedPwd = password_hash($hashedPwd, PASSWORD_DEFAULT);




    $randomsecret = generateRandomString();
    $date = date('m/d/Y h:i:s a', time());
    // number of 's' indicate number of values? for some reason, and i used placeholder for all the unsupplied values


    mysqli_stmt_bind_param($stmt, "ssssssssss", $username, $hashedPwd, $firstname, $lastname, $email, $phonenumber, $date, $primaryschool, $favouritefood, $randomsecret);
    mysqli_stmt_execute($stmt);
    //closes the connection
    mysqli_stmt_close($stmt);

    $_SESSION['username'] = $username;
    $_SESSION['loginstate'] = "Z";


    header("location: ../swapproj/googleauthentication");
    exit();
}
// Function to generate random secret for google auth
function generateRandomString($length = 16)
{
    $characters = '234567QWERTYUIOPASDFGHJKLZXCVBNM';
    $charactersLength = strlen($characters);
    $randomString = '';
    for ($i = 0; $i < $length; $i++) {
        $randomString .= $characters[rand(0, $charactersLength - 1)];
    }
    return $randomString;
}


//////////////LOGIN FUNCTIONS////////////////
//checks for empty input boxes
function emptyInputLogin($username, $pwd)
{
    $result = false;
    if (empty($username) || empty($pwd)) {
        $result = true;
    } else {
        $result = false;
    }
    return $result;
}

//checks for email otp
function verification2fa($email)
{
    $result = false;
    if (empty($username) || empty($pwd)) {
        $result = true;
    } else {
        $result = false;
    }
    return $result;
}

//logs in user whether username or email is used
function loginUser($conn, $username, $pwd, $remember)
{
    $uidExists = uidExists($conn, $username, $username);

    if ($uidExists === false) {
        header("location: ../swapproj/login?error=wronglogin");
        exit();
    }

    $pepper = "AWiokdfnkFNKKHHDBJXLL28838jkuiu54859dnkkmid93E1928485";
    $pwdHashed = $uidExists["user_password"];
    $pwd = hash_hmac("sha256", $pwd, $pepper);
    $pwd = hash("sha256", hash("sha256", $pwd));
    $checkPwd = password_verify($pwd, $pwdHashed);

    if ($checkPwd === false) {
        header("location: ../swapproj/login?error=wronglogin");
        exit();
    } elseif ($checkPwd === true) {
        // OTP email

        $vc = new VerificationCode($uidExists["username_email"]);
        $vc->sendMail(); // MAIL SENT SUCCESSFULLY

        //Taking the current time
        $_SESSION['start'] = time();
        //Setting the time to end session
        $_SESSION['expire'] = $_SESSION['start'] + (200);

        //session superglobal
        $_SESSION["userid"] = $uidExists["user_id"];
        $_SESSION["username"] = $uidExists["user_username"];
        $_SESSION['useremail'] = $uidExists['username_email'];
        $_SESSION["role"] = $uidExists["user_role"];
        $_SESSION["loginstate"] = "A";
        $_SESSION['LAST_ACTIVE_TIME'] = time();

        $array['role'] = $uidExists["user_role"];
        $array['username'] = $uidExists["user_username"];
        $array['loginstate'] = 'A';
        $array['userid'] = $uidExists["user_id"];

        $encrypted = jwtencrypt($array);
        if ($remember == true) {
            //they checked "rememberme"
            setCookieSameSite('jwt', $encrypted, time() + 86400); //1 day

        } elseif ($remember == false) {
            setCookieSameSite('jwt', $encrypted, 0); //0 means cookie dies when closed

        }






        header("location: ../swapproj/emailverification");
        exit();
    }
}


function jwtencrypt($array)
{
    $objpages = new Pages();
    $encrypted = $objpages->auth($array);

    if ($encrypted) {
        $encrypted = $encrypted['token'];
    }


    return $encrypted;
}

function jwtdecrypt()
{
    require_once $_SERVER['DOCUMENT_ROOT'] . '/swapproj/auth/pages.php';


    if (isset($_COOKIE['jwt'])) {
        $token = $_COOKIE['jwt'];
    }




    $objpages = new Pages();
    $decrypted = $objpages->read($token);
    if ($decrypted) {
        $decrypted = json_decode(json_encode($decrypted), true);
    }

    return $decrypted;
}

function jwtupdate($newarray)
{
    $pages = new Pages();
    if (isset($_COOKIE['jwt'])) {

        $cookie = $_COOKIE['jwt'];
        $cookie = $pages->read($cookie); //verify if token valid. returns null if its not

        if ($cookie != null) {


            $cookie = json_decode(json_encode($cookie), true); //convert to array
            $array = $cookie['array'];

            foreach ($newarray as $key => $val) {
                $array[$key] = $val;
            }




            //update instead of replace
            $iat = $cookie['iat'];
            $exp = $cookie['exp'];

            $updateInfo = $pages->updateauth($array, $iat, $exp);
            $updateInfo = $updateInfo['token'];


            //push to cookie
            setCookieSameSite('jwt', $updateInfo, time() + 86400);
        }
    }
}




//checks for empty input boxes
function failedCaptcha($captcha)
{
    $result = false;
    if (!isset($captcha) || empty($captcha)) {
        //runs if captcha is empty

        $result = "empty captcha";
        echo $result;
    } else {
        //runs if captcha received input
        $secret = '6LceTzMdAAAAAOpz-EsYoCKZGnAXCzF3lv-FsFfF';

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, 'https://www.google.com/recaptcha/api/siteverify?secret=' . $secret . '&response=' . $captcha);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $response = curl_exec($ch);
        curl_close($ch);
        $response = json_decode($response);

        if ($response->success) {
            // What happens when the CAPTCHA was entered incorrectly
            $result = true;
            echo "bad captcha";
        } else {
            // Your code here to handle a successful verification
            $result = false;
            echo "good captcha";
        }
    }
    return $result;
}


function setCookieSameSite(string $name, string $value, $expire)
{


    $domain = 'www.swapamc.com';
    $samesite = 'Strict';
    $secure = true;
    $httponly = true;
    $path = '/';


    if (PHP_VERSION_ID < 70300) {
        setcookie($name, $value, $expire, $path . '; samesite=' . $samesite, $domain, $secure, $httponly);
        return;
    } else
        setcookie($name, $value, [
            'expires' => $expire,
            'path' => $path,
            'domain' => $domain,
            'samesite' => $samesite,
            'secure' => $secure,
            'httponly' => $httponly,
        ]);
}

function emptyInputShippingAdd($name, $email, $phonenumber, $address, $unit, $zip)
{
    $result = false;
    if (empty($name) || empty($email) || empty($phonenumber) || empty($address) || empty($unit) || empty($zip)) {
        $result = true;
    } else {
        $result = false;
    }
    return $result;
}
function viewDefaultShippingAdd($conn)
{

    $userid = $_SESSION["userid"];
    $query = $conn->prepare("SELECT user_shipping_id, user_shipping_name, user_shipping_number, user_shipping_email, user_shipping_address, user_shipping_postalcode, user_shipping_unitnumber, user_shipping_default FROM user_shippinginformation WHERE user_shipping_userid = $userid AND user_shipping_default = 1");
    $stmt = mysqli_stmt_init($conn);
    if (!$query->execute()) {
        header("location: ../swapproj/checkout?error=stmtfailed");
        exit();
    }
    if ($query->execute()) {
        $result = $query->get_result();
        if ($result->num_rows > 0) {
            while ($row = mysqli_fetch_array($result)) {

                $shippingaddress = $row;
                return $shippingaddress;
            }
        } else {
            $shippingaddress = 0;
            return $shippingaddress;
        }
    }
    $conn->close();
}
function cartpurchased($conn)
{
    $selectedcarts = $_SESSION['cart'];
    $harry = implode(',', $selectedcarts);

    $bundledidrandom = $_SESSION['bundledid'];
    $query = $conn->prepare("UPDATE mydb.user_cart SET  mydb.user_cart.purchased = 1 , mydb.user_cart.bundled=$bundledidrandom WHERE  mydb.user_cart.cart_id IN (" . $harry . ") ");
    $stmt = mysqli_stmt_init($conn);
    if (!$query->execute()) {
        header("location: ../swapproj/checkout?error=stmtfailed");
        exit();
    }
    if ($query->execute()) {

        // header("location: https://www.swapamc.com/swapproj/checkout?payment=success ");
    }
    $query->close();
}
function selectCreditCardInfo($conn, $userid)
{
    $query = $conn->prepare("SELECT MAX(user_creditcardinfo_id) FROM mydb.user_creditcardinfo WHERE user_creditcardinfo_userid = " . $userid);
    $stmt = mysqli_stmt_init($conn);
    if (!$query->execute()) {
        header("location: ../swapproj/checkout?error=stmtfailed");
    }
    $ccinfo = 0;
    if ($query->execute()) {
        $query->bind_result($ccinfo);
        $query->fetch();
    }
    return $ccinfo;
    $conn->close();
}


function addIntoPastPurchase($conn)
{
    session_start();
    $userid = $_SESSION["userid"];
    $defaultshippingid = $_SESSION['defaultshippingid'];
    $purchasequantity = sizeof($_SESSION["cart"]);
    $purchasetime = date('Y-m-d H:i:s', time());
    $totalprice = $_SESSION['totalpricegst'];
    $creditcardinfo = selectCreditCardInfo($conn, $userid);
    $bundledidrandom =  $_SESSION['bundledid'];
    $purchasestatus = "1";

    $sql = "INSERT INTO mydb.user_past_purchases(user_id, user_shipping, user_creditcards, purchase_time,purchase_quantity, purchase_cost, purchase_status, cart_bundled)
    VALUES (?,?,?,?,?,?,?,?)";

    $stmt = mysqli_stmt_init($conn);
    if (!mysqli_stmt_prepare($stmt, $sql)) {
        header("location: https://www.swapamc.com/swapproj/checkout?error=stmtfailed");
        exit();
    }
    mysqli_stmt_bind_param($stmt, "ssssssss", $userid, $defaultshippingid, $creditcardinfo, $purchasetime, $purchasequantity, $totalprice, $purchasestatus, $bundledidrandom);
    if (mysqli_stmt_execute($stmt)) {
        header("location: https://www.swapamc.com/swapproj/checkout?payment=success ");
    }
    $conn->close();
}


function addShippingAdd($conn, $name, $phonenumber, $email, $address, $zip, $unit)
{
    session_start();
    $userid = $_SESSION["userid"];
    $sql = "INSERT INTO user_shippinginformation (user_shipping_name, user_shipping_number, user_shipping_email, user_shipping_address, user_shipping_postalcode, user_shipping_unitnumber, user_shipping_userid,user_shipping_default ) VALUES (?,?,?,?,?,?,$userid,0)";
    $stmt = mysqli_stmt_init($conn);

    if (!mysqli_stmt_prepare($stmt, $sql)) {
        header("location: ../swapproj/checkout/addshippingaddress?error=stmtfailed");
        echo "error";
        exit();
    }

    mysqli_stmt_bind_param($stmt, "ssssss", $name, $phonenumber, $email, $address, $zip, $unit);
    mysqli_stmt_execute($stmt);
    //closes the connection
    mysqli_stmt_close($stmt);

    header("location: ../swapproj/checkout/addshippingaddress?=success");
    echo "success added";
    exit();
}

function addCreditCard($conn, $cname,  $expmonth, $expyear, $cardtype)
{
    session_start();
    $userid = $_SESSION["userid"];
    $sql = "INSERT INTO user_creditcardinfo (user_creditcardinfo_nameoncard,user_creditcardinfo_userid, user_creditcardinfo_expirymonth, user_creditcardinfo_expiryyear, user_creditcardinfo_cardtype)  VALUES (?,$userid,?,?,?)";
    $stmt = mysqli_stmt_init($conn);

    if (!mysqli_stmt_prepare($stmt, $sql)) {
        header("location: ../swapproj/checkout?error=stmtfailed");
        exit();
    }

    mysqli_stmt_bind_param($stmt, "ssss", $cname,  $expmonth, $expyear, $cardtype);
    mysqli_stmt_execute($stmt);
    //closes the connection
    mysqli_stmt_close($stmt);
}


function invalidPostalCode($zip)
{
    $result = false;
    if (!preg_match("/\d{6}/", $zip)) {
        $result = true;
    } else {
        $result = false;
    }
    return $result;
}

function emptyDefaultShipping($sa)
{

    $sa = $_SESSION['shippingaddress'];
    var_dump($sa);
    $result = false;
    if (empty($sa) or $sa = "0") {
        $result = true;
    } else if ($sa = "1") {
        $result = false;
    }
    return $result;
}

function emptyCart($emptycarts)
{
    $result = false;
    $emptycarts = $_SESSION['cart'];
    var_dump($emptycarts);
    if (empty($emptycarts)) {
        $result = true;
    } else {
        $result = false;
    }
    return $result;
}

function emptyInputPayment($cname, $number, $expmonth, $expyear, $cvc)
{
    $result = false;
    if (empty($cname) || empty($number) || empty($expmonth) || empty($expyear) || empty($cvc)) {
        $result = true;
    } else {
        $result = false;
    }
    return $result;
}
function invalidCName($cname)
{
    $result = false;
    if (!preg_match("^[a-zA-Z]*$", $cname)) {
        $result = true;
    } else {
        $result = false;
    }
    return $result;
}

function invalidExpMonth($expmonth)
{
    if (!is_numeric($expmonth) || $expmonth < 1 || $expmonth > 12) {

        $result = true;
    } else {
        $result = false;
    }
    return $result;
}


// Get the current year    
function invalidExpYear($expyear)
{
    $currentYear = date('Y');

    settype($currentYear, 'integer');


    if (!is_numeric($expyear) || $expyear < $currentYear || $expyear > $currentYear + 10) {

        $result = true;
    } else {
        $result = false;
    }
    return $result;
}


function invalidCVC($cvc)
{
    $result = false;
    if (!preg_match("/^[0-9]{3,4}$/", $cvc)) {
        $result = true;
    } else {
        $result = false;
    }
    return $result;
}


